[package]
name = "building-sunlight-simulator"
version = "3.2.0"
description = "Offline building sunlight simulation and analysis"
authors = ["SeanWong17"]
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
